import { useEffect, useState } from 'react';

export const languageOptions=[['English','en'],['Español','es'],['العربية','ar'],['Русский','ru'],['Deutsch','de'],['Português','pt'],['Français','fr'],['Italiano','it'],['w języku polskim','pl'],['Türk','tr'],['Український','uk'],['中文','zh']];
export const copy={
  en:{products:'Products',technology:'Technology',company:'Company',contact:'Contact',talk:'Talk to us',choose:'Choose a',surface:'surface.',productLibrary:'PRODUCT LIBRARY',start:'Start with a material family, then explore the exact models, specifications and images inside.',productDetail:'PRODUCT DETAIL',specs:'TECHNICAL SPECIFICATIONS',made:'Made to',perform:'perform.',back:'Back to products',allFamilies:'All product families',view:'View model',request:'Request a quote',companyKicker:'SO-FINE / ESTABLISHED 2005',companyTitle:'20 years of industrial expertise.',companyText:'',techKicker:'THE SO-FINE DIFFERENCE',techTitle:'Innovation. Quality. Service. Commitment.',contactKicker:"LET'S MAKE SOMETHING LAST",contactTitle:'Start with a surface.'},
  es:{products:'Productos',technology:'Tecnología',company:'Empresa',contact:'Contacto',talk:'Hablemos',choose:'Elige una',surface:'superficie.',productLibrary:'CATÁLOGO DE PRODUCTOS',start:'Elige una familia de materiales y explora sus modelos, especificaciones e imágenes.',productDetail:'DETALLES DEL PRODUCTO',specs:'ESPECIFICACIONES TÉCNICAS',made:'Diseñado para',perform:'rendir.',back:'Volver a productos',allFamilies:'Todas las familias',view:'Ver modelo',request:'Solicitar cotización',companyText:'',techKicker:'LA DIFERENCIA SO-FINE',techTitle:'La precisión es la base.',contactKicker:'HAGAMOS QUE DURE',contactTitle:'Comienza con una superficie.'},
  de:{products:'Produkte',technology:'Technologie',company:'Unternehmen',contact:'Kontakt',talk:'Kontaktieren',choose:'Wähle eine',surface:'Oberfläche.',productLibrary:'PRODUKTKATALOG',start:'Wähle eine Materialfamilie und entdecke Modelle, Spezifikationen und Bilder.',productDetail:'PRODUKTDETAILS',specs:'TECHNISCHE DATEN',made:'Entwickelt für',perform:'Leistung.',back:'Zurück zu Produkten',allFamilies:'Alle Produktfamilien',view:'Modell ansehen',request:'Angebot anfordern',companyText:'',techKicker:'DER SO-FINE UNTERSCHIED',techTitle:'Präzision ist die Grundlage.',contactKicker:'LASSEN WIR ES DAUERN',contactTitle:'Beginne mit einer Oberfläche.'},
  fr:{products:'Produits',technology:'Technologie',company:'Entreprise',contact:'Contact',talk:'Nous contacter',choose:'Choisissez une',surface:'surface.',productLibrary:'CATALOGUE PRODUITS',start:'Choisissez une famille de matériaux et découvrez ses modèles, spécifications et images.',productDetail:'DÉTAIL DU PRODUIT',specs:'SPÉCIFICATIONS TECHNIQUES',made:'Conçu pour',perform:'performer.',back:'Retour aux produits',allFamilies:'Toutes les familles',view:'Voir le modèle',request:'Demander un devis',companyText:'',techKicker:'LA DIFFÉRENCE SO-FINE',techTitle:'La précision est le fondement.',contactKicker:'FAISONS DURER LES CHOSES',contactTitle:'Commencez par une surface.'},
  zh:{products:'产品',technology:'技术',company:'公司',contact:'联系',talk:'联系我们',choose:'选择一款',surface:'表面材料。',productLibrary:'产品库',start:'选择材料系列，继续查看对应型号、技术参数和产品图片。',productDetail:'产品详情',specs:'技术参数',made:'为性能而',perform:'打造。',back:'返回产品',allFamilies:'全部产品系列',view:'查看型号',request:'询价',companyText:'',techKicker:'SO-FINE 的优势',techTitle:'精度，是一切的基础。',contactKicker:'让项目持续创造价值',contactTitle:'从一面表面开始。'}
};
export function useLanguage(){const[lang,setLang]=useState(()=>localStorage.getItem('sofine-language')||'en');useEffect(()=>{const onChange=()=>setLang(localStorage.getItem('sofine-language')||'en');window.addEventListener('sofine-language-change',onChange);return()=>window.removeEventListener('sofine-language-change',onChange)},[]);const change=value=>{localStorage.setItem('sofine-language',value);window.dispatchEvent(new Event('sofine-language-change'))};return {lang,change,t:key=>(copy[lang]||copy.en)[key]??copy.en[key]??key}}
